version: '3.8'

services:
  split-bill-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4321:4321"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=4321
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - split-bill-network

networks:
  split-bill-network:
    driver: bridge
